[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
rust_decimal = { version = "1.36.0", features = ["serde-with-str"] }
rust_decimal_macros = "1.36"
serde = { version = "1.0.217", features = ["derive"] }
serde_cbor = "0.11.2"
fjall = "2.5.0"
csv = "1.3.1"
